vespa/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

import starcatalogue.views
import waspstatic.views

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('exoplanets/', TemplateView.as_view(template_name='waspstatic/exoplanets.html'), name='exoplanets'),
    path('vespa/', starcatalogue.views.IndexListView.as_view(), name='vespa'),
    path('vespa/browse/', starcatalogue.views.StarListView.as_view(), name='browse'),
    path('vespa/download/', starcatalogue.views.DownloadView.as_view(), name='download'),
    path('vespa/export/', starcatalogue.views.GenerateExportView.as_view(), name='generate_export'),
    path('vespa/export/<str:pk>/', starcatalogue.views.DataExportView.as_view(), name='view_export'),
    path('vespa/source/<str:swasp_id>/', starcatalogue.views.SourceView.as_view(), name='view_source'),
    path('about/', waspstatic.views.AboutView.as_view(), name='about'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starcatalogue/models.py
import datetime
import logging
import urllib
import uuid

import numpy

from django.db import models
from django.utils import timezone

import astropy.io.fits as fits
from astropy import units
from astropy.coordinates import SkyCoord
from astropy.stats import sigma_clip
from astropy.timeseries import TimeSeries

from celery.result import AsyncResult
from humanize.time import naturaldelta
from humanize import naturalsize

from .fields import SPointField


OUTLIER_SIGMA_CLIP = 5
FLUX_MAX_CLIP = 2e5

logger = logging.getLogger(__name__)


def export_upload_to(instance, filename):
    return f'exports/{instance.id.hex[:3]}/{instance.id.hex}/{filename}'

def star_upload_to(instance, filename):
    return f'sources/{instance.superwasp_id}/v{instance.CURRENT_IMAGE_VERSION}_{filename}'

def lightcurve_upload_to(instance, filename):
    return f'sources/{instance.star.superwasp_id}/v{instance.CURRENT_IMAGE_VERSION}_{filename}'


class ImageGenerator(object):
    def get_or_generate_image(self, image_attr, generation_task, default=None):
        image_not_present = not image_attr or not self.image_version
        image_outdated = self.image_version and self.image_version < self.CURRENT_IMAGE_VERSION
        if image_not_present or image_outdated:
            if (
                not self.images_celery_task_id
                or AsyncResult(self.images_celery_task_id).ready()
                or not self.image_celery_started
                or self.image_celery_started < (timezone.now() - datetime.timedelta(minutes=5))
            ):
                self.images_celery_task_id = generation_task.delay(self.id).id
                self.image_celery_started = timezone.now()
                self.save()
            if image_not_present:
                return default
        elif self.images_celery_task_id:
            AsyncResult(self.images_celery_task_id).forget()
        return image_attr.url


class Star(models.Model, ImageGenerator):
    CURRENT_IMAGE_VERSION = 0.92
    CURRENT_STATS_VERSION = 0.31

    superwasp_id = models.CharField(unique=True, max_length=26)
    fits_file = models.FileField(null=True, upload_to=star_upload_to)
    fits_celery_task_id = models.UUIDField(null=True)
    fits_celery_started = models.DateTimeField(null=True)
    fits_error_count = models.IntegerField(default=0)

    image_file = models.ImageField(null=True, upload_to=star_upload_to)
    images_celery_task_id = models.UUIDField(null=True)
    image_version = models.FloatField(null=True)
    image_celery_started = models.DateTimeField(null=True)

    _min_magnitude = models.FloatField(null=True)
    _mean_magnitude = models.FloatField(null=True)
    _max_magnitude = models.FloatField(null=True)
    stats_version = models.FloatField(null=True)

    location = SPointField(null=True)

    @classmethod
    def outlier_clip(cls, flux):
        return sigma_clip(
            numpy.ma.masked_greater(
                numpy.ma.masked_less(
                    flux,
                    -FLUX_MAX_CLIP,
                ),
                FLUX_MAX_CLIP
            ),
            sigma=OUTLIER_SIGMA_CLIP
        )

    @property
    def coords_str(self):
        return self.superwasp_id.replace('1SWASP', '')

    @property
    def coords(self):
        return SkyCoord(self.coords_str, unit=(units.hour, units.deg))
    
    @property
    def coords_quoted(self):
        return urllib.parse.quote(self.coords_str)

    @property
    def ra(self):
        return self.coords.ra.to_string(units.hour)
    
    @property
    def dec(self):
        return self.coords.dec

    @property
    def ra_quoted(self):
        coords = self.coords_str
        return urllib.parse.quote(f'{coords[1:3]}:{coords[3:5]}:{coords[5:10]}')

    @property
    def dec_quoted(self):
        coords = self.coords_str
        return urllib.parse.quote(f'{coords[10:13]}:{coords[13:15]}:{coords[15:]}')

    def set_location(self):
        coords = self.coords
        self.location = (coords.ra.to_value(), coords.dec.to_value())
        self.save()

    @property
    def lightcurves(self):
        return self.foldedlightcurve_set.all().order_by('period_length')

    @property
    def fits(self):
        if (
            not self.fits_file
            and (
                not self.fits_celery_task_id
                or AsyncResult(self.fits_celery_task_id).ready()
                or not self.fits_celery_started
                or self.fits_celery_started < (timezone.now() - datetime.timedelta(minutes=5))
            )
        ):
            self.fits_celery_task_id = download_fits.apply_async(
                (self.id,),
                expires=300,
            ).id
            self.fits_celery_started = timezone.now()
            self.save()
            return None

        if self.fits_celery_task_id:
            AsyncResult(self.fits_celery_task_id).forget()

        return self.fits_file

    @property
    def fits_file_naturalsize(self):
        return naturalsize(self.fits_file.size)

    @property
    def timeseries(self):
        if not self.fits:
            return

        try:
            with fits.open(self.fits.path) as fits_file:
                hjd_col = fits.Column(name='HJD', format='D', array=fits_file[1].data['TMID']/86400 + 2453005.5)
                lc_data = fits.BinTableHDU.from_columns(fits_file[1].data.columns + fits.ColDefs([hjd_col]))
                return TimeSeries.read(lc_data, time_column='HJD', time_format='jd')
        except OSError as e:
            logger.warning(f'Could not read FITS file {self.fits.path} for star {self.id}')
            logger.warning(str(e))
            self.fits_file = None
            self.fits_error_count += 1
            self.save()

    @property
    def image_location(self):
        return self.get_image_location()

    def get_image_location(self):
        return self.get_or_generate_image(self.image_file, generate_star_images)

    @property
    def cerit_url(self):
        return f'https://wasp.cerit-sc.cz/search?objid={self.coords_quoted}&radius=1&radiusUnit=deg&limit=10'

    @property
    def simbad_url(self):
        return f'http://simbad.u-strasbg.fr/simbad/sim-coo?Coord={self.ra_quoted}+{self.dec_quoted}&Radius=2&Radius.unit=arcmin&submit=submit+query'
    
    @property
    def asassn_url(self):
        return f'https://asas-sn.osu.edu/photometry?ra={self.ra_quoted}&dec={self.dec_quoted}&radius=2'

    def get_magnitude(self, attr_name='_mean_magnitude'):
        if (
            self.stats_version is None or
            self.stats_version < self.CURRENT_STATS_VERSION or 
            getattr(self, attr_name) is None
        ):
            self.calculate_magnitudes()

        return getattr(self, attr_name)

    def calculate_magnitudes(self):
        agg_funcs = {
            '_mean_magnitude': lambda x: x.mean(),
            '_min_magnitude': lambda x: x.min(),
            '_max_magnitude': lambda x: x.max(),
        }
        timeseries = self.timeseries
        if not timeseries:
            return
        flux = Star.outlier_clip(timeseries['TAMFLUX2'])
        for attr_name, agg_func in agg_funcs.items():
            mag = 15 - 2.5 * numpy.log10(agg_func(flux))
            setattr(self, attr_name, mag)
        self.stats_version = self.CURRENT_STATS_VERSION
        self.save()

    @property
    def mean_magnitude(self):
        return self.get_magnitude('_mean_magnitude')

    @property
    def max_magnitude(self):
        return self.get_magnitude('_max_magnitude')

    @property
    def min_magnitude(self):
        return self.get_magnitude('_min_magnitude')


class FoldedLightcurve(models.Model, ImageGenerator):
    PULSATOR = 1
    EA_EB = 2
    EW = 3
    ROTATOR = 4
    UNKNOWN = 5
    JUNK = 6
    CLASSIFICATION_CHOICES = [
        (PULSATOR, 'Pulsator'),
        (EA_EB, 'EA/EB'),
        (EW, 'EW'),
        (ROTATOR, 'Rotator'),
        (UNKNOWN, 'Unknown'),
        (JUNK, 'Junk'),
    ]

    CERTAIN = 0
    UNCERTAIN = 1
    PERIOD_UNCERTAINTY_CHOICES = [
        (CERTAIN, 'Certain'),
        (UNCERTAIN, 'Uncertain'),
    ]

    CURRENT_IMAGE_VERSION = 0.91

    star = models.ForeignKey(to=Star, on_delete=models.CASCADE)

    period_number = models.IntegerField()
    period_length = models.FloatField(null=True)
    sigma = models.FloatField(null=True)
    chi_squared = models.FloatField(null=True)
    classification = models.IntegerField(choices=CLASSIFICATION_CHOICES, null=True)
    period_uncertainty = models.IntegerField(choices=PERIOD_UNCERTAINTY_CHOICES, null=True)
    classification_count = models.IntegerField(null=True)

    image_file = models.ImageField(null=True, upload_to=lightcurve_upload_to)
    thumbnail_file = models.ImageField(null=True, upload_to=lightcurve_upload_to)
    images_celery_task_id = models.UUIDField(null=True)
    image_version = models.FloatField(null=True)
    image_celery_started = models.DateTimeField(null=True)

    @property
    def natural_period(self):
        return naturaldelta(self.period_length)

    @property
    def image_location(self):
        return self.get_image_location()

    def get_image_location(self):
        return self.get_or_generate_image(
            self.image_file,
            generate_lightcurve_images,
            self.zooniversesubject.image_location,
        )

    @property
    def thumbnail_location(self):
        return self.get_thumbnail_location()

    def get_thumbnail_location(self):
        return self.get_or_generate_image(
            self.thumbnail_file,
            generate_lightcurve_images,
            self.zooniversesubject.thumbnail_location,
        )

    @property
    def timeseries(self):
        if not self.star.timeseries:
            return
        return self.star.timeseries.fold(
            period=self.period_length * units.second,
        )


class ZooniverseSubject(models.Model):
    zooniverse_id = models.IntegerField(unique=True)

templates/starcatalogue/download.html
{% extends 'base.html' %}

templates/starcatalogue/index.html
{% extends "starcatalogue/foldedlightcurve_list.html" %}

{% block title %}VeSPA: The SuperWASP Variable Star Photometry Archive{% endblock %}
{% block pagetitle %}VeSPA: The SuperWASP Variable Star Photometry Archive{% endblock %}

{% block content %}

<p class="lead">This interface makes available SuperWASP lightcurves for periodic variable stars that have been classified by Citizen Scientists using the <a href="https://www.zooniverse.org/projects/ajnorton/superwasp-variable-stars">SuperWASP Variable Stars Zooniverse project</a>. It will be updated with new classification results every 6 months. Last update on dd-mm-yyyy.</p>

<h2>Browse the Catalogue</h2>

{{ block.super }}

{% endblock %}

templates/starcatalogue/pagination.html
{% load starcatalogue_tags %} 

<div class="col">
  <nav aria-label="Catalogue navigation">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'browse' %}?{% param_replace page=1 %}">First</a></li>  
        <li class="page-item"><a class="page-link" href="{% url 'browse' %}?{% param_replace  page=page_obj.previous_page_number %}">Previous</a></li> 
      {% endif %}
      <li class="page-item"><span class="page-link">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="{% url 'browse' %}?{% param_replace page=page_obj.next_page_number %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'browse' %}?{% param_replace page=page_obj.paginator.num_pages %}">Last</a></li>
      {% endif %}
    </ul>
  </nav>
</div>

templates/starcatalogue/star_detail.html
{% extends 'base.html' %}
{% load starcatalogue_tags %} 

{% block title %}{{ object.superwasp_id }}{% endblock %}

{% block pagetitle %}{{ object.superwasp_id }}{% endblock %}

{% block headEnd %}
<link rel="stylesheet" href="https://aladin.u-strasbg.fr/AladinLite/api/v2/latest/aladin.min.css">
{% endblock %}

{% block content %}
<div class="row mt-5">
{% if object.image_location %}

    <div class="col">
        <p><img src="{{ object.image_location }}" alt=""></p>
    </div>

{% endif %}
    <div class="col">
        <div id="aladin-lite-div" style="width:100%;height:300px;"></div>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">RA</th>
                    <td colspan=>{{ object.ra }}</td>
                </tr>
                <tr>
                    <th scope="row">Dec</th>
                    <td>{{ object.dec }}</td>
                </tr>
                <tr>
                    <th scope="row">Minimum Magnitude</th>
                    <td>{% if not object.min_magnitude|isnan %}{{ object.min_magnitude|floatformat:2 }}{% else %}Less than limit (V~15){% endif %}</td>
                </tr>
                <tr>
                    <th scope="row">Maximum Magnitude</th>
                    <td>{% if not object.max_magnitude|isnan %}{{ object.max_magnitude|floatformat:2 }}{% else %}Less than limit (V~15){% endif %}</td>
                </tr>
                <tr>
                    <th scope="row">Mean Magnitude</th>
                    <td>{% if not object.mean_magnitude|isnan %}{{ object.mean_magnitude|floatformat:2 }}{% else %}Less than limit (V~15){% endif %}</td>
                </tr>
                {% if object.fits %}
                <tr>
                    <th scope="row">Raw data</th>
                    <td><a href="{{ object.fits.url }}"><i class="bi bi-download mr-2"></i> Download FITS ({{ object.fits_file_naturalsize }})</a></td>
                </tr>
                {% endif %}
                <tr>
                    <th scope="row">Links</th>
                    <td>
                        <ul class="list-unstyled">
                            <li><a href="{{ object.cerit_url }}">CERiT</a></li>
                            <li><a href="{{ object.simbad_url }}">Simbad</a></li>
                            <li><a href="{{ object.asassn_url }}">ASAS-SN</a></li>
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for lightcurve in object.lightcurves %}
        <div class="col">
          <div class="card shadow-sm mb-4">
              <a href="#lightcurve-{{ lightcurve.id }}"><img src="{{ lightcurve.image_location }}" class="card-img-top"></a>
            <div class="card-body">
              <p class="card-text">{{ lightcurve.get_classification_display }}, {{ lightcurve.natural_period }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
</div>


{% for lightcurve in object.lightcurves %}
    <h2 class="mt-5" id="lightcurve-{{ lightcurve.pk }}"><a href="#lightcurve-{{ lightcurve.pk }}"><i class="bi bi-link"></i></a> {{ object.superwasp_id }} folded at {{ lightcurve.natural_period }}</h2>

    <div class="row mb-5">
        <div class="col">
            <img src="{{ lightcurve.image_location }}" alt="" style="width: 100%; max-height: auto;">
        </div>
        <div class="col">
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Period (sec)</th>
                        <td>{{ lightcurve.period_length }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Majority Classification</th>
                        <td>{{ lightcurve.get_classification_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Classification count</th>
                        <td>{{ lightcurve.classification_count }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Folding flag</th>
                        <td>{{ lightcurve.get_period_uncertainty_display }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sigma</th>
                        <td>{{ lightcurve.sigma }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Chi Squared</th>
                        <td>{{ lightcurve.chi_squared }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Links</th>
                        <td>
                            <ul class="list-unstyled">
                                <li><a href="https://www.zooniverse.org/projects/ajnorton/superwasp-variable-stars/talk/subjects/{{ lightcurve.zooniversesubject.zooniverse_id }}">Zooniverse Talk</a></li>
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endfor %}

{% endblock %}

{% block bodyEnd %}
<script type="text/javascript" src="https://aladin.u-strasbg.fr/AladinLite/api/v2/latest/aladin.min.js" crossorigin="anonymous" charset="utf-8"></script>
<script type="text/javascript">
    var aladin = A.aladin('#aladin-lite-div', {survey: "P/DSS2/color", fov:0.17, target: "{{ object.coords_str }}"});
</script>
{% endblock %}

templates/starcatalogue/star_list.html
{% extends "base.html" %}

{% block title %}Browse the Catalogue{% endblock %}

{% block content %}

<div class="row mt-5">
  <div class="col">


    <div class="btn-group">
      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Magnitude
        </button>
        <div class="dropdown-menu px-3" aria-labelledby="dropdownMenuButton">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Min</span>
            </div>
            <input type="text" class="form-control" placeholder="" aria-label="Minimum" aria-describedby="basic-addon1">
          </div>    
          
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Max</span>
            </div>
            <input type="text" class="form-control" placeholder="" aria-label="Maximum" aria-describedby="basic-addon1">
          </div> 
        </div>
        </div>
        <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Period
        </button>
        <div class="dropdown-menu px-3" aria-labelledby="dropdownMenuButton">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Min</span>
            </div>
            <input type="text" class="form-control" placeholder="" aria-label="Minimum" aria-describedby="basic-addon1">
          </div>    
          
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Max</span>
            </div>
            <input type="text" class="form-control" placeholder="" aria-label="Maximum" aria-describedby="basic-addon1">
          </div> 
        </div>
        </div>
        <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Variable type
        </button>
        <div class="dropdown-menu px-3" aria-labelledby="dropdownMenuButton">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" checked>
            <label class="form-check-label" for="defaultCheck1">
              Pulsator
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" checked>
            <label class="form-check-label" for="defaultCheck1">
              Rotator
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" checked>
            <label class="form-check-label" for="defaultCheck1">
              EA/EB
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" checked>
            <label class="form-check-label" for="defaultCheck1">
              EW
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" checked>
            <label class="form-check-label" for="defaultCheck1">
              Unknown
            </label>
          </div>
        </div>
        </div>
        <button type="button" class="btn btn-secondary">Download</button>
    </div>
  </div>
  {% include "starcatalogue/pagination.html" %}

    <div class="modal fade" id="lightcurveModal" tabindex="-1" aria-labelledby="lightcurveModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="lightcurveModalLabel">Lightcurve</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p><img src="#" alt="" style="width: 100%; height: auto;"></p>
            </div>
          </div>
        </div>
      </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">SuperWASP ID</th>
                <th scope="col">Period (seconds)</th>
                <th scope="col">RA</th>
                <th scope="col">Dec</th>
                <th scope="col">Classification</th>
                <th scope="col">Zooniverse Talk</th>
                <th scope="col">Lightcurve</th>
            </tr>
        </thead>
        <tbody>
        {% for star in object_list %}
            {% for lightcurve in star.foldedlightcurve_set.all %}
            <tr>
                <td>{{ star.superwasp_id }}</td>
                <td>{{ lightcurve.period_length }}</td>
                <td>{{ star.ra }}</td>
                <td>{{ star.dec }}</td>
                <td>{{ lightcurve.get_classification_display }}</td>
                <td><a href="https://www.zooniverse.org/projects/ajnorton/superwasp-variable-stars/talk/subjects/{{ lightcurve.zooniversesubject.zooniverse_id }}">View on Talk</a></td>
                <td>{% if lightcurve.zooniversesubject.image_location %}<a href="#" data-toggle="modal" data-target="#lightcurveModal" data-url="{{ lightcurve.zooniversesubject.image_location }}" data-superwasp-id="{{ star.superwasp_id }}"><img src="{{ lightcurve.zooniversesubject.thumbnail_location }}" alt="" style="width: 100px; height: auto;"></a>{% endif %}</td>
            </tr>
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>

    {% include "starcatalogue/pagination.html" %}

    <div class="jumbotron">
        <h2 class="display-4">Acknowledgements</h2>

        <p class="lead">The SuperWASP project is currently funded and operated by Warwick University and Keele University, and was originally set up by Queen’s University Belfast, the Universities of Keele, St. Andrews and Leicester, the Open University, the Isaac Newton Group, the Instituto de Astrofisica de Canarias, the South African Astronomical Observatory and by STFC.</p>

        <p class="lead">The Zooniverse project on SuperWASP Variable Stars is led by Andrew Norton (The Open University) and builds on work he has done with his former postgraduate students Les Thomas, Stan Payne, Marcus Lohr and Paul Greer, and current postgraduate students Heidi Thiemann & Adam McMaster.</p>

        <p class="lead">The Zooniverse project on SuperWASP Variable Stars was developed with the help of the ASTERICS Horizon2020 project. ASTERICS is supported by the European Commission Framework Programme Horizon 2020 Research and Innovation action under grant agreement n.653477</p>
    </div>

{% endblock %}

{% block bodyEnd %}
<script type="text/javascript">
$('#lightcurveModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var url = button.data('url') // Extract info from data-* attributes
    var superwasp_id = button.data('superwasp-id')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this)
    modal.find('.modal-title').text('Lightcurve for ' + superwasp_id)
    modal.find('.modal-body img').attr('src', url)
  })
</script>
{% endblock %}